# Generated by Django 5.0.1 on 2024-02-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default='2024-02-08'),
            preserve_default=False,
        ),
    ]
