# Generated by Django 5.0.1 on 2024-02-15 12:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
